version: '3.8'

services:
  frontend:
    container_name: img2code_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/Img2Code
      - /workspaces/Img2Code/node_modules
    ports:
      - "3000:3000"
    command: npm run dev